# Name of workflow
name: Development workflow

# Trigger
on:
  pull_request:
    branches:
      - dev

# Jobs to carry out
jobs:
  deployment:
    # Runner (OS)
    runs-on: ubuntu-latest

    #specify environment
    environment:
      name: Development
      url: https://toodle-do-dev.netlify.app/

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      # Install NodeJS
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Run npm install and build on our code
      - run: npm ci
      - run: npm run build --if-present

      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
